################################## GENERAL #####################################

# Sentinel listening port.
port 26379

# Run in foreground (Docker mode).
daemonize no

# Logging level.
loglevel notice

# Logs to stdout.
logfile ""

# Directory for Sentinel state files.
dir "/data"

################################## MONITORING ##################################

# Monitor Valkey master.
# Format: name host port quorum
sentinel monitor mymaster valkey-master 6379 2

# Time before master is considered down (milliseconds).
sentinel down-after-milliseconds mymaster 5000

# Maximum failover duration (milliseconds).
sentinel failover-timeout mymaster 60000

# Number of replicas synchronized at the same time.

################################## SECURITY ####################################

# Maximum ACL log entries.
acllog-max-len 128

# Disable dynamic Sentinel script reconfiguration.
sentinel deny-scripts-reconfig yes

################################## DNS #########################################

# Allow Docker service name resolution.
sentinel resolve-hostnames yes

# Announce hostnames instead of IPs.
sentinel announce-hostnames yes
# Generated by CONFIG REWRITE
latency-tracking-info-percentiles 50 99 99.9
user default on nopass sanitize-payload ~* &* +@all
sentinel myid ec3c55263a0deaa08390020dcc6cbe79077c73cf
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
sentinel current-epoch 0

sentinel known-replica mymaster 172.20.0.7 6379

sentinel known-replica mymaster 172.20.0.4 6379

sentinel known-replica mymaster 172.20.0.6 6379

